"""Глобальные константы приложения."""

ACTIVE_JOB_STATUSES = ("queued", "scheduled", "processing")
TERMINAL_JOB_STATUSES = ("completed", "failed")
ALL_JOB_STATUSES = ACTIVE_JOB_STATUSES + TERMINAL_JOB_STATUSES

DEFAULT_RANDOM_MIN_MINUTES = 30
DEFAULT_RANDOM_MAX_MINUTES = 120
DEFAULT_MIN_GAP_MINUTES = 90
DEFAULT_LOOKAHEAD_DAYS = 14

__all__ = [
    "ACTIVE_JOB_STATUSES",
    "TERMINAL_JOB_STATUSES",
    "ALL_JOB_STATUSES",
    "DEFAULT_RANDOM_MIN_MINUTES",
    "DEFAULT_RANDOM_MAX_MINUTES",
    "DEFAULT_MIN_GAP_MINUTES",
    "DEFAULT_LOOKAHEAD_DAYS",
]
